todo/urls.py
from django.urls import path
from .views import (
    TaskListView,
    TagListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskCompleteView,
)

urlpatterns = [
    path(
        "",
        TaskListView.as_view(),
        name="task-list",
    ),
    path(
        "tags/",
        TagListView.as_view(),
        name="tag-list",
    ),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create",
    ),

    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update",
    ),
    path(
        "tasks/<int:pk>/complete/",
        TaskCompleteView.as_view(),
        name="complete-task",
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete",
    ),
    path(
        "tags/create/",
        TagCreateView.as_view(),
        name="tag-create",
    ),
    path(
        "tags/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tag-update",
    ),
    path(
        "tags/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tag-delete",
    ),
]

app_name = "todo"

todo_list_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = ([
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

todo/models.py
from django.db import models
from datetime import datetime, timedelta


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]


class Task(models.Model):
    content = models.CharField(max_length=255, unique=True)
    created_datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    def __str__(self):
        return self.content

    class Meta:
        ordering = ["is_done", "-created_datetime"]

todo/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic
from .models import Tag, Task


class TaskListView(generic.ListView):
    model = Task
    context_object_name = "task_list"
    template_name = "todo/task_list.html"


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:task-list")


class TaskCompleteView(generic.UpdateView):
    model = Task
    fields = ["is_done"]

    def post(self, request, *args, **kwargs):
        task = self.get_object()
        task.is_done = not task.is_done
        task.save()
        return redirect("todo:task-list")


class TagListView(generic.ListView):
    model = Tag
    context_object_name = "tag_list"
    template_name = "todo/tag_list.html"


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Todo List</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
  <div class="container-fluid">
      <div class="row">
          <div class="col-sm-2">
              {% block sidebar %}
                  {% include "includes/sidebar.html" %}
              {% endblock %}
          </div>
          <div class="col-sm-10 ">
              {% block content %}{% endblock %}
          </div>
      </div>
  </div>
</body>
</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item">
    <a href="{% url 'todo:task-list' %}">Home</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'todo:tag-list' %}">Tags</a>
  </li>
</ul>

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete this tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tag List
    <a href="{% url 'todo:tag-create' %}" class="btn btn-primary link-to-page">
      Add
    </a>
  </h1>

  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
              {{ tag.name }}
          </td>
          <td>
              <a href="{% url 'todo:tag-update' pk=tag.id %}">
                Update
              </a>
            </td>
            <td>
              <a style="color: red"
                href="{% url 'todo:tag-delete' pk=tag.id %}">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no tags in the list.</p>
  {% endif %}
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete this task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    TODO list
    <a href="{% url 'todo:task-create' %}" class="btn btn-primary link-to-page">
      Add Task
    </a>
  </h1>

  {% if task_list %}
    <table class="w-100">
      {% for task in task_list %}
        <tr>
         <td>
          <ul style="list-style: none">
           <li>
            <b><h5>{{ task.content }}</h5>
                {% if task.is_done %}
                  <span class="text-success">Done</span>
                  {% else %}
                  <span class="text-danger">Not done</span>
                {% endif %}
            </b><br />
            <span style="font-weight: 500">
              {{ task.created_datetime }}</span>
            <span style="color: #ad0a87; font-weight: 500">
              {% if task.deadline %}
                {{ task.deadline }}
                {% else %}
                  No deadline
              {% endif %}
            </span>
            <br />
             <span style="font-weight: 500; color: lightslategrey" >Tags:</span>
              {% for tag in task.tags.all %}
                <span class="bg-secondary text-white opacity-4">{{ tag.name }}</span>
              {% endfor %}
            <br />
            <a
              href="{% url 'todo:task-update' pk=task.id %}"
              style="color: blue;">Update
            </a>
            <a
              href="{% url 'todo:task-delete' pk=task.id %}"
              style="color: red;">Delete
            </a>
            </li>
            <hr />
          </ul>
         </td>
         <td>
          <form method="post" action="{% url 'todo:complete-task' pk=task.pk %}">
            {% csrf_token %}
            {% if task.is_done %}
              <input
                  type="submit"
                  class="btn btn-sm btn-secondary text-nowrap mt-3 link-to-page"
                  value="Undo">
            {% else %}
              <input
                  type="submit"
                  class="btn btn-sm btn-success text-nowrap mt-3 link-to-page"
                  value="Complete">
            {% endif %}
          </form>
        </td>
      {% endfor %}
    </table>

  {% else %}
    <p>There are no tasks in this list</p>
  {% endif %}
{% endblock %}